### ISSUE TITLE
Release for Ruby 2.7 test fixes?

### ISSUE THREAD

**Issue by cbaines** [jeremyevans/minitest-hooks#19]
Hey,

I was looking at building the GNU Guix package for minitest-hooks with Ruby 2.7, and noticed the tests failed. It looks like this is fixed with some unreleased commits.

I thought I'd ask if you'd consider doing a new release with the current unreleased changes? If not, no problem, I can look at using the git repository as a source for the Guix package.

Thanks,

Chris

**Comment by jeremyevans** [comment]
The unreleased changes only fix the tests for minitest-hooks itself, they don't affect usage of minitest-hooks.  Hopefully you can understand that it doesn't make sense to me to release a new minitest-hooks version with no user-visible changes.  I don't understand why you would want to use a version from git, as the content of the `lib` has not changed, but there should be no harm in doing so.
