### ISSUE TITLE
[config issue] Not work with minitest spec.

### ISSUE THREAD

**Issue by zw963** [jeremyevans/minitest-hooks#21]
Hi, i use minitest-hooks on one rails project, it works quite well with ActiveSupport::TestCase.

after then, i want to use this in my own Roda + sequel project and replace `database_cleaner-sequel` with this gem.

i use minitest spec + old assert assert, i want archive same effect as a around_all like hook to run all my test in transactions.

like this when work with rails test.

```rb
def around_all
  DB.transaction do
    super 
  end
end
```

Following is some attempt.

```rb
# test helper

ENV['RACK_ENV'] = 'test'
require 'minitest/autorun'
require 'minitest/pride'
require 'minitest/hooks'
require "rack/test"

OUTER_APP = Rack::Builder.parse_file("config.ru").first.freeze.app

class Minitest::Test
  MiniTest::Spec.register_spec_type(/.*/, Minitest::HooksSpec)
  # include Minitest::Hooks
  include Rack::Test::Methods

  def app
    OUTER_APP
  end

describe 'something' do
    around(:all) do |&block|
      DB.transaction(:rollback=>:always) do
        super(&block)
      end
    end
  end
end
```

```rb
# my test

require 'test_helper'

describe 'insider histories' do
  it 'test postgres read committed mode default lock' do
    create(:insider_history, number_of_shares: 200)

    # ....

    assert_equal 180.0, InsiderHistory.last.number_of_shares
  end
end
```

But both not work, even, i move ``describe 'something' do`` code into one spec file, still meet primary key conflict issue when run second time, thank you.

**Comment by jeremyevans** [comment]
I think your main problem comes from `describe 'something' do` in your test helper example.  You are defining an `around(:all)` in an empty spec suite, which is going to have no effect outside that suite.  I'm guessing this comes from copying and pasting the example in the README without reading the documentation before the example to understand what it does (hint, the `in a suite` part is imporant.).

You almost never want `around(:all)` without `around` when implementing transactional testing.  If you are using minitest/spec, and want all spec suites to support minitest-hooks, then use `require 'minitest/hooks/default'`.  

If you have problems, you should probably run with a Sequel Database logger, so you can see whether the BEGIN/COMMIT queries are being sent.  

Since you are using this for Sequel testing, my advice would be to follow Sequel's testing guide, as that gives you an example you can copy and paste: http://sequel.jeremyevans.net/rdoc/files/doc/testing_rdoc.html#label-Transactional+testing+with+savepoints

**Comment by zw963** [comment]
> I'm guessing this comes from copying and pasting the example in the README without reading the documentation before the  example to understand what it does (hint, the `in a suite` part is imporant.).
 
Sorry for that, yesterday, i create this issue, the time is 3' clock before dawn on china, chi stopping thinking ... in fact, today is 2:00 now.

Add following code works for me use minitest describe spec + sequel. (some test case failed because use fiber concurrency plugins, but that is expected)

```rb
require 'minitest/hooks/default'

class Minitest::HooksSpec
  def around
    DB.transaction(:rollback=>:always, :savepoint=>true, :auto_savepoint=>true){super}
  end

  def around_all
    DB.transaction(:rollback=>:always){super}
  end
end
```

BTW,  as document said:

```
and by using transactions per test suite, you only pay the cost to load the data once for the test suite, and it is automatically rolled back after the test suite completes.
```

I never add code like following in my describe block

```rb
describe "some large test suite" do
  before(:all) do
    # ...
  end
end
```

But, following test no primary key conflict error and can pass.

```rb
require 'test_helper'

describe 'routes/insiders/show' do
  it 'should failed' do
    create(:insider, id: 1)  # use Fabricator
    get '/insiders/1'
    refute last_response.ok?
  end

  it 'should succss' do
    insider = create(:insider, id: 1)
    create(:insider_history, insider: insider)
    get '/insiders/1'
    assert last_response.ok?
  end
end
```
Could you please tell me why? thank you.

**Comment by jeremyevans** [comment]
I would first try running with a Database logger, so you can see what queries are being sent.  If that doesn't help you determine the cause of the problem, can you put together a minimal self-contained example, that doesn't use anything besides minitest-hooks and Sequel?  The example needs to be self-contained, so you need to create the tables, etc. before the code with the two specs.  If you can do that, I can take a look.

**Comment by zw963** [comment]
https://gist.github.com/1592c1f81f64c1cc2934dc7337d0ca58

Please check,l AFAIK,  `it "test" do` run same transaction as `it "test2" do`, right?

so, insider1 and insider2 should conflict?

**Comment by jeremyevans** [comment]
Neither spec fails, nor should they.  Both specs run in the same transaction, but each in a separate savepoint that is rolled back after the spec finishes.  In general, you want each spec to be isolated from all other specs, which is what is happening in this case.  Why would you want a spec that works in isolation but fails depending on whether another spec has run before it and didn't clean up properly?

**Comment by zw963** [comment]
> Neither spec fails, nor should they. Both specs run in the same transaction, but each in a separate savepoint that is rolled back after the spec finishes. In general, you want each spec to be isolated from all other specs, which is what is happening in this case. Why would you want a spec that works in isolation but fails depending on whether another spec has runore it and didn't clean up properly?

All right, i guess i misunderstood following code before.

```rb

describe "some large test suite" do
  before(:all) do
    DB[:table].import # Large number of rows
  end
end
```
 
I thought I had to write code in before(:all) block to make transaction work.

thank you

**Comment by jeremyevans** [comment]
No, you don't have to have a `before(:all)` block.  It's just that if you have a `before(:all)` block, it will be run inside the transaction, before any of the specs in the suite are executed.

**Comment by zw963** [comment]
> No, you don't have to have a `before(:all)` block. It's just that if you have a `before(:all)` block, it will be run inside the transaction, before any of the specs in the suite are executed.

Still not clear for me.

So, what you means is:

### Following code run in transaction 1


```rb
describe "some large test suite" do
  before(:all) do
    DB[:table].import # Large number of rows
  end
end
```

### following code run in transaction 2

```rb

describe 'routes/insiders/show' do
  it 'should failed' do
    create(:insider, id: 1)  # use Fabricator
    get '/insiders/1'
    refute last_response.ok?
  end

  it 'should succss' do
    insider = create(:insider, id: 1)
    create(:insider_history, insider: insider)
    get '/insiders/1'
    assert last_response.ok?
  end
end
```

Right?

**Comment by jeremyevans** [comment]
Yes, with the config using the link I sent, each suite uses its own transaction, and each spec its own savepoint in that transaction.  You can use a Database logger to confirm.
