### ISSUE TITLE
`before :all` / `after :all` / `around :all` are called once per subclass but should not

### ISSUE THREAD

**Issue by grosser** [jeremyevans/minitest-hooks#8]
this code calls do_expensive_stuff multiple times, ideally it should only do so once,
this might be hard to implement because minitest randomizes subclass run order ... https://github.com/grosser/maxitest/blob/master/lib/maxitest/let_all.rb might be an inspiration on how to pull that off

```Ruby
before(:all) { do_expensive_stuff }

it { xxx }

describe "xxx" do
  it { xxx }
end
```

**Comment by jeremyevans** [comment]
This isn't a bug, it's expected.  the inner describe creates a new class, and before(:all) is called once per class (including subclasses).

Sorry for taking for so long to respond to this, I must have missed this when responding to #7.
